-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create students table
CREATE TABLE IF NOT EXISTS students (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  class_period text NOT NULL DEFAULT '1',
  birthday date,
  google_id text,
  google_email text,
  period text,
  is_active boolean DEFAULT true
);

-- Create teachers table
CREATE TABLE IF NOT EXISTS teachers (
  id bigserial PRIMARY KEY,
  email text UNIQUE NOT NULL,
  name text
);

-- Insert your teacher email
INSERT INTO teachers (email) VALUES ('aromero@vanguardacademy.net') ON CONFLICT (email) DO NOTHING;

-- Create assignments table
CREATE TABLE IF NOT EXISTS assignments (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  date date NOT NULL,
  type text NOT NULL,
  periods text[],
  subject text DEFAULT 'assignment',
  google_classroom_id text,
  google_classroom_link text,
  max_points integer DEFAULT 100,
  six_weeks_period VARCHAR(3) CHECK (six_weeks_period ~ '^[1-6]SW$'),
  status text DEFAULT 'not_started',
  completed boolean DEFAULT false,
  completed_at timestamptz,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_assignments_six_weeks ON assignments(six_weeks_period);

-- Create grades table
CREATE TABLE IF NOT EXISTS grades (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  student_id bigint REFERENCES students(id) ON DELETE CASCADE NOT NULL,
  period text NOT NULL,
  grade text NOT NULL,
  assignment_id uuid REFERENCES assignments(id) ON DELETE CASCADE,
  extra_points smallint DEFAULT 0,
  google_submission_id text,
  last_synced timestamp,
  created_at timestamptz DEFAULT now()
);

-- Create assignment_tags table
CREATE TABLE IF NOT EXISTS assignment_tags (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  assignment_id uuid REFERENCES assignments(id) ON DELETE CASCADE,
  student_id bigint REFERENCES students(id) ON DELETE CASCADE,
  period text NOT NULL,
  tag_type text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Create assignment_flags table
CREATE TABLE IF NOT EXISTS assignment_flags (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  assignment_id uuid REFERENCES assignments(id) ON DELETE CASCADE,
  student_id bigint REFERENCES students(id) ON DELETE CASCADE,
  flag_type text NOT NULL,
  notes text,
  created_at timestamptz DEFAULT now()
);

-- Create google_classroom_links table
CREATE TABLE IF NOT EXISTS google_classroom_links (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  assignment_id uuid REFERENCES assignments(id) ON DELETE CASCADE,
  google_course_id text NOT NULL,
  google_coursework_id text NOT NULL
);

-- Create extra_points table
CREATE TABLE IF NOT EXISTS extra_points (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  assignment_id uuid REFERENCES assignments(id) ON DELETE CASCADE,
  student_id bigint REFERENCES students(id) ON DELETE CASCADE,
  period text NOT NULL,
  points smallint NOT NULL
);

-- Create assignment_notes table
CREATE TABLE IF NOT EXISTS assignment_notes (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  assignment_id uuid REFERENCES assignments(id) ON DELETE CASCADE,
  student_id bigint REFERENCES students(id) ON DELETE CASCADE,
  notes text
);

-- Create course_mappings table
CREATE TABLE IF NOT EXISTS course_mappings (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  google_course_id text NOT NULL,
  period text NOT NULL DEFAULT '1',
  subject text NOT NULL,
  setup_completed boolean DEFAULT false,
  setup_completed_at timestamp,
  UNIQUE (google_course_id, period)
);

-- Create student_mappings table
CREATE TABLE IF NOT EXISTS student_mappings (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  google_id text NOT NULL UNIQUE,
  google_email text,
  student_id bigint REFERENCES students(id) ON DELETE CASCADE,
  period text NOT NULL DEFAULT '1'
);

-- Create absences table
CREATE TABLE IF NOT EXISTS absences (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  assignment_id uuid REFERENCES assignments(id) ON DELETE CASCADE,
  student_id bigint REFERENCES students(id) ON DELETE CASCADE,
  period text NOT NULL
);

-- Create messages table
CREATE TABLE IF NOT EXISTS messages (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at timestamptz DEFAULT now(),
  sender text,
  recipient text,
  content text,
  is_read boolean DEFAULT false
);

-- Enable RLS for all tables
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE grades ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignment_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignment_flags ENABLE ROW LEVEL SECURITY;
ALTER TABLE google_classroom_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE extra_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignment_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE absences ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Drop old policies if they exist
DROP POLICY IF EXISTS "Allow authenticated read access" ON students;
DROP POLICY IF EXISTS "Allow authenticated read access" ON teachers;
DROP POLICY IF EXISTS "Allow authenticated read access" ON assignments;
DROP POLICY IF EXISTS "Allow authenticated read access" ON grades;
DROP POLICY IF EXISTS "Allow authenticated read access" ON assignment_tags;
DROP POLICY IF EXISTS "Allow authenticated read access" ON assignment_flags;
DROP POLICY IF EXISTS "Allow authenticated read access" ON google_classroom_links;
DROP POLICY IF EXISTS "Allow authenticated read access" ON extra_points;
DROP POLICY IF EXISTS "Allow authenticated read access" ON assignment_notes;
DROP POLICY IF EXISTS "Allow authenticated read access" ON course_mappings;
DROP POLICY IF EXISTS "Allow authenticated read access" ON student_mappings;
DROP POLICY IF EXISTS "Allow authenticated read access" ON absences;
DROP POLICY IF EXISTS "Allow authenticated read access" ON messages;

DROP POLICY IF EXISTS "Allow users to manage their own data" ON students;
DROP POLICY IF EXISTS "Allow users to manage their own data" ON teachers;
DROP POLICY IF EXISTS "Allow users to manage their own data" ON assignments;
DROP POLICY IF EXISTS "Allow users to manage their own data" ON grades;
DROP POLICY IF EXISTS "Allow users to manage their own data" ON assignment_tags;
DROP POLICY IF EXISTS "Allow users to manage their own data" ON assignment_flags;
DROP POLICY IF EXISTS "Allow users to manage their own data" ON google_classroom_links;
DROP POLICY IF EXISTS "Allow users to manage their own data" ON extra_points;
DROP POLICY IF EXISTS "Allow users to manage their own data" ON assignment_notes;
DROP POLICY IF EXISTS "Allow users to manage their own data" ON course_mappings;
DROP POLICY IF EXISTS "Allow users to manage their own data" ON student_mappings;
DROP POLICY IF EXISTS "Allow users to manage their own data" ON absences;
DROP POLICY IF EXISTS "Allow users to manage their own data" ON messages;

-- Create permissive policies
CREATE POLICY "Allow all access for authenticated users" ON students FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated users" ON teachers FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated users" ON assignments FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated users" ON grades FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated users" ON assignment_tags FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated users" ON assignment_flags FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated users" ON google_classroom_links FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated users" ON extra_points FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated users" ON assignment_notes FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated users" ON course_mappings FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated users" ON student_mappings FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated users" ON absences FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated users" ON messages FOR ALL TO authenticated USING (true) WITH CHECK (true);
