












































      return;      console.error('No submissions found');    if (!submissions.data.studentSubmissions?.[0]) {    });      courseWorkId: assignment.id!      courseId,    const submissions = await classroom.courses.courseWork.studentSubmissions.list({    console.log('Testing with assignment:', assignment.title);    const assignment = courseWork.data.courseWork[0];    }      return;      console.error('No coursework found');    if (!courseWork.data.courseWork?.[0]) {    });      courseId    const courseWork = await classroom.courses.courseWork.list({    console.log('Fetching coursework...');    const courseId = '708732866408';    });      auth: oauth2Client      version: 'v1',    const classroom = google.classroom({    });      refresh_token: process.env.GOOGLE_REFRESH_TOKEN      access_token: process.env.GOOGLE_ACCESS_TOKEN,    oauth2Client.setCredentials({    );      'http://localhost:3000/api/auth/callback/google'      process.env.GOOGLE_CLIENT_SECRET,      process.env.GOOGLE_CLIENT_ID,    const oauth2Client = new OAuth2Client(  try {async function testGradeSync() {dotenv.config({ path: '.env.local' });import { OAuth2Client } from 'google-auth-library';import dotenv from 'dotenv';import { google } from 'googleapis';