import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";
import { NextAuthProvider } from '@/providers/auth';
import { Navigation } from '@/components/Navigation';
import { Toaster } from '@/components/ui/toaster';  // Fixed quote
import { UserBanner } from '@/components/UserBanner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NextAuthProvider>
            <div className="min-h-screen flex flex-col">
              <header className="border-b">
                <div className="container mx-auto">
                  <Navigation />
                </div>
              </header>
              <main className="flex-1">
                <div className="container mx-auto">
                  <UserBanner />
                  {children}
                </div>
              </main>
            </div>
          </NextAuthProvider>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
