create table staar_scores (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id) not null,
  grade integer not null,
  score integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(student_id, grade)
);

-- Import data from CSV
create or replace function import_staar_scores() returns void as $$
begin
  insert into staar_scores (student_id, grade, score)
  select 
    "LocalId"::bigint as student_id,
    7 as grade,
    "STAAR MA07 PcntScore"::integer as score
  from temp_staar_scores
  where "STAAR MA07 PcntScore" is not null;
end;
$$ language plpgsql;
